---
title: "final_g19"
author: "Chloe Pham, Carolina Flores, Pamela Garcia"
date: "5/9/2022"
output: html_document
---
#Chloe Pham 
#Q1 & Q2
```{r}
#1
library(ggplot2)
load("~/final_gr19/ThreeCancers.RData")

#i) 587 subjects
nrow(GeneExp)

#ii) 100
ncol(GeneExp)

#iii) 7.311357
mean(GeneExp$Gene2)

#iv) 
ggplot(data=GeneExp, mapping=aes(x=Gene45, y=Gene68)) +
geom_point()

#v) 0.9159255
cor.test(x=GeneExp$Gene45,y=GeneExp$Gene68, method="pearson")


#2

#i)
boxplot(GeneExp$Gene15 ~ CancerType, col = c("red",
"green", "blue"), ylab= "Gene15")

#ii)the red box represents the interquartile range (middle 50%), aka the patients with BRCA and have Gene15 expression levels of approximately 4 to 6.

#iii) BRCA and KIRC have outliers. 

#iv) KIRC has the smallest median expression level.
```

#Pamela Garcia 
#Q3 & Q4
```{r}
#Q3
y = as.numeric(CancerType == 'KIRC')

# (i) 
set.seed(10)
x <- GeneExp$Gene15
noise <- rnorm(n= 30, mean = 0, sd = .1)
y = as.numeric(CancerType == 'KIRC')

df <- data.frame(list(explanatory= x, observed_val = y))
plot(x = x, y= y)
lines(x = x, y =  as.numeric(CancerType == 'KIRC'))

fit <- lm(formula = observed_val ~ explanatory, data = df)
summary(fit)

plot(x = x, y= y)
# plot estimated function
lines(x = x, y =  0.599 + .07*x, col = "red")
# plot true function
lines(x = x, y = 0.6 + 0.1*x, col = "blue")

# (ii)
  # (a) The estimated coefficient of the Gene15 variable is 0.599
  # (b) The p-value associated to the coefficient is 1.1e-15
  # (c) The p-value corresponds to the null hypothesis that gene expression of gene 15 and a patient having KIRC cancer do not correlate.
  # (d) We can conclude that, based on the p-value, the null hypothesis is rejected. The expression of gene 15 and a patient having KIRC cancer how correlation.

# (iii) B0 is 0.6 and B1 is 0.1

#Q4
# (i)
set.seed(1)
data <- GeneExp
gene.kmeans = kmeans(x = data, centers = 3)

# (ii)
table(gene.kmeans$cluster, CancerType)

# (iii) Cluster 2 best represents patients with KIRC cancer

# (iv) Cluster 2 best represents the gene expression profile of a KIRC patient, while Cluster 1 from the k-means result shows the gene expression profile of a LUAD patient. 
```

#Carolina Flores
#Q5
```{r}
#Q5
#i)
GeneExp.dist = dist(x=GeneExp[1:10,], method='euclidean')

#ii)
gene.hclust = hclust(d=GeneExp.dist, method='complete')

#iii)
GeneExp.dist.mat = as.matrix(GeneExp.dist)
#print(GeneExp.dist.mat)

#iv)
x = GeneExp.dist.mat[1,]
y = GeneExp.dist.mat[2,]


d_ist = x-y
d_ist = d_ist^2
d_ist = sum(d_ist)
d_ist = sqrt(d_ist)


#v)
z = GeneExp[1,]
a = GeneExp[2,]

euc_d = sqrt(sum((z-a)^2))

#vi)
#Subject 9 has the smallest distance to Subject 5 

#vii)
# Two linkage criteria's are 
#1. Average 
#2. Single

#viii)
#Using complete linkage the distance from subject 6 to the sub cluster containing subject 1 and 10 is the maximum distance in the cluster being 17.99.
```

